---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-admin
  namespace: default
subjects:
- kind: User
  name: ed.paillard@gmail.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: stephane.n-da@epitech.eu
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: theoygo20@outlook.fr
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: nicolas.houilon@epitech.eu
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: maxence.marqui@epitech.eu
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io