apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-kubequest
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: chart-app
    repoURL: https://nolygonnintheo.github.io/chart-app/
    targetRevision: 0.2.0
    helm:
      releaseName: chart-app

        
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sample-app-ns