apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-loki
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.11
    helm:
      releaseName: loki
      valuesObject:
        loki:
          enabled: true
          isDefault: false
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-kubequest"
              cert-manager.io/common-name: loki.k3s.lifoto.co
            hosts:
              - host: loki.k3s.lifoto.co
                paths:
                - /
            tls:
              - secretName: loki-tls
                hosts:
                  - loki.k3s.lifoto.co
          config:
            compactor:
              retention_enabled: true
        promtail:
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          rbac:
            pspEnabled: false
          containerSecurityContext:
            privileged: True
            allowPrivilegeEscalation: True
          tolerations:
            - key: "CriticalAddonsOnly"
              operator: Exists
              effect: "NoExecute"
        grafana:
          sidecar:
            datasources:
              enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring