apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-trivy
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts
    targetRevision: 2.9.11
    helm:
      releaseName: trivy
  destination:
    server: "https://kubernetes.default.svc"
    namespace: trivy